### ISSUE TITLE
SPARK for MAC

### ISSUE THREAD

**Issue by masakiwestriver** [monadius/spark-abm#1]
Hi,
We have encountered a problem when we tried to use the program on MACs.

It works great on Windows machines, but when we start SPARK Manager.jar on MACs,
we can't find and open projects by clicking "File -> Open new project".
We tried both universal version and Mac version of SPARK, but neither of them worked. 
The latest version of Java (as of Dec 2020) is running on Mac OSX.   

Your help will be greatly appreciated.

Thank you.

Masaki

**Comment by monadius** [comment]
I would like to clarify: Is the menu item "Open project..." missing or does it not work?

Here is a screenshot of SPARK Manager.jar running on my macOS Big Sur:
![Screen Shot 2021-01-13 at 9 39 50 PM](https://user-images.githubusercontent.com/7527525/104549569-02a3e080-55e8-11eb-9d6c-21949fc94cb5.png)

Do you see the same user interface as shown in the screenshot?

I know that there is an issue with compiling SPARK models on macOS (the "Compile" button does not yield any results). I am working on an updated version of SPARK which will address this issue.

**Comment by masakiwestriver** [comment]
Thank you very much for your comments.  "Open project" does exist, but it does not take us to the folder where xml files are stored, while it opens the unzipped folder in Windows PCs... Thank you.

**Comment by monadius** [comment]
When I click "Open project..." on my MAC, I get the following dialog:
![Screen Shot 2021-01-13 at 10 25 57 PM](https://user-images.githubusercontent.com/7527525/104552923-8c56ac80-55ee-11eb-9e75-705795a4f3ac.png)

Then I can navigate to existing SPARK models and open them:
![Screen Shot 2021-01-13 at 10 26 19 PM](https://user-images.githubusercontent.com/7527525/104552965-a3959a00-55ee-11eb-84d2-ad78f66564c5.png)

Can you see the "Open" dialog? Is it possible to navigate to different locations with this dialog?

**Comment by masakiwestriver** [comment]
One of us uses the following OS and java versions.
OS: macOS Big Sur 11.1
Java: 1.8.0_271-b09
In the picture below, "開く" means "Open".
I'm asking this user if he can navigate to different locations from "Open dialog", but if I remember correctly, he said he could not.
Thanks a lot.
 
<img width="625" alt="Nishi" src="https://user-images.githubusercontent.com/37122918/104664826-91614c00-5713-11eb-8af7-718451cd2c78.png">

**Comment by masakiwestriver** [comment]
The environment of another is:  
OS: 10.15.7
Java: 15.0.1
According to the screenshot, it seems to be the same.
I'm asking the same question to this user. I will let you know once I hear from them.
![Naka](https://user-images.githubusercontent.com/37122918/104665254-46940400-5714-11eb-9f72-500764389da6.png)

**Comment by masakiwestriver** [comment]
I just heard form one of them. It seems like they can navigate but can't find the unzipped SPARK folder....

**Comment by monadius** [comment]
Did they unzip SPARK into Desktop or Download folders? The access to these folders is restricted in recent versions of macOS. Try to copy SPARK into a different location (for instance, to ~/SPARK). I also was able to open Desktop files by running SPARK from Terminal: 
```bash
cd SPARK_FOLDER_NAME
java -jar "SPARK Manager.jar"
```

**Comment by masakiwestriver** [comment]
This screenshot probably shows the folders under the initial folder that we see by clicking "Open project".
I wonder if you could tell where it could be? Seems like they have no idea where and what these folders are... 
I will tell them to place SPARK folder somewhere else other than Desktop or Download folders.

**Comment by masakiwestriver** [comment]
![IMG_3005](https://user-images.githubusercontent.com/37122918/104673181-8a8f0500-5724-11eb-8cec-df4340c59dd1.jpg)
Sorry I forgot to upload the pic.

**Comment by monadius** [comment]
The last item in the drop down list (not visible in your screenshot) should be Macintosh HD. Select it and then go to Users -> user name -> Spark location (should be not in Desktop, Documents, or Downloads).

**Comment by masakiwestriver** [comment]
After replacing the folder, they found the xml file! Thank you.
But when they click the file, they got the following error message.
I wonder what's wrong with this...? Thank you.

<img width="1192" alt="start1" src="https://user-images.githubusercontent.com/37122918/104675624-376b8100-5729-11eb-9f4f-e732e360f267.png">

**Comment by monadius** [comment]
It seems that SPARK itself is located in a restricted folder. Try to copy SPARK to a different location.

**Comment by monadius** [comment]
You may also try to run SPARK from Terminal. Open the Terminal app and then type:
```
cd spark_location
java -jar "SPARK Manager.jar"
```
(Replace spark_location with the path to SPARK).

**Comment by masakiwestriver** [comment]
Thank you! I told them to try. Just one quick question, Does the folder location matter, if we run SPARK from Terminal?

**Comment by monadius** [comment]
If you run SPARK from terminal, then it gets the same access rights as the Terminal app. On my computer, Terminal has access to Desktop and other restricted locations. I'm not sure if it is true for your Mac.

**Comment by masakiwestriver** [comment]
This message popped up after running...

<img width="727" alt="N2" src="https://user-images.githubusercontent.com/37122918/104680246-c4670800-5732-11eb-91df-9941e20d09b9.png">

**Comment by monadius** [comment]
Error messages are not good in the current version of SPARK: It is not clear from this error message which file contains an error. Make sure that all files in your SPARK project have "agent", "model", or "class" at the first line (excluding lines with comments).

**Comment by masakiwestriver** [comment]
I think it is the xml file in CirrhosisModel in "SPARK_1.2.003_universal" distributed through your article. I wonder if you could check it.... Sorry

**Comment by monadius** [comment]
The model which I have on my computer runs without any issues. My version of the model may be different from the model distributed with the article. But I cannot find a download link to the published model. The link in the article (http://www.frontiersin.org/Journal/10.3389/fbioe.2014.00018/abstract) opens the article itself. Do you have a link to the published model? Or just attach the archive to your comment.

**Comment by masakiwestriver** [comment]
Thank you, I really appreciate your help.
The link is  http://www.pitt.edu/~cirm/spark/models/LFABM.zip
If it does not work, I can attach the zip folder.

**Comment by monadius** [comment]
The new SPARK website is located at http://www.mirmresearch.net/spark/default.asp
But the model source was not moved to the new site.

**Comment by masakiwestriver** [comment]
Does that mean the one we obtained from the link in your article (http://www.pitt.edu/~cirm/spark/models/LFABM.zip) is the latest version?

**Comment by monadius** [comment]
Could you please attach the archive that you have to a comment. I want to compare it with the version which I have.

**Comment by masakiwestriver** [comment]
[LFABM.zip](https://github.com/monadius/spark-abm/files/5827862/LFABM.zip)
[SPARK_1.1a_mac.zip](https://github.com/monadius/spark-abm/files/5827865/SPARK_1.1a_mac.zip)
The first one is the universal version that we can download from the article. And the second one is Mac version from previous SPARK website. Either of them had the same problem and did not work on Mac when we tried...  (We copied CirrhosisModel folder from Universal version to Mac version. Should it be ok?)

**Comment by monadius** [comment]
SPARK_1.1a_mac fails with the same error message as in your [comment](https://github.com/monadius/spark-abm/issues/1#issuecomment-760632004). SPARK_1.1a_mac is outdated and should not be used.

The universal SPARK version from LFABM.zip works on my Mac. I did the following:
1) Unpacked LFABM.zip into a nonrestricted folder (not into Downloads, Documents, or Desktop).
1) Installed JDK 8 from [here](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot). Later versions of JDK will not work with SPARK (I'm going to publish an updated SPARK version soon which will work with any modern JDK version). If you already have JDK 8 installed then you may skip this step. If you have a different version of Java installed then it may be necessary to switch to Java 8 after it is installed. In Terminal type `java -version`. If the version is not `1.8` then follow [this instructions](https://medium.com/@devkosal/switching-java-jdk-versions-on-macos-80bc868e686a) to switch to Java 8.
1) Navigated to the SPARK folder in the Terminal app and ran `java -jar "SPARK Manager.jar"`
1) Selected Options > Options In the SPARK Manager menu. Then set paths to spark-core.jar and spark-external.jar: SPARK folder/lib/spark-core.jar and SPARK folder/lib/spark-external.jar. (I clicked `...` buttons to open file dialogs to set paths.)
1) Opened CirrhosisModel in SPARK Manager and clicked `Start`.

Please let me know if you encounter any issues with these steps.

**Comment by masakiwestriver** [comment]
Thank you so much! I will tell them to try and let you know how it went. I really appreciate your help.

**Comment by masakiwestriver** [comment]
Sorry, this must be a naive question, but when we go to the web site you suggested and choose "OpenJDK8(LTS)" and "HotSpot", then it gives us 4 options as shown below. First of all, "HotSpot" is the right option? I did a quick search on google, but I could not be sure of it. Second, which file out of those 4 should we choose? Thank you for your help.

![java](https://user-images.githubusercontent.com/37122918/104907768-ef6a8980-59c8-11eb-8d0a-ba2e7b1180a6.jpg)

**Comment by monadius** [comment]
HotSpot is the right choice. Please download the first file (JDK - 105 MB, .pkg). I also updated my previous comment: I added information about configuring paths in SPARK Manager (step 4).

**Comment by masakiwestriver** [comment]
Thank you so much. I'm asking the Mac users to try. I will let you know. Thanks a lot!

**Comment by masakiwestriver** [comment]
I just heard that they all succeeded to run. Thank you very much for your kind help. I really appreciate your support.

**Comment by monadius** [comment]
I have prepared an updated version of SPARK: https://github.com/monadius/spark-abm/releases/tag/v1.4.0

You don't need to use this new version if everything works with the old SPARK release. The new version may be useful if you want to run SPARK with JDK 9 or later. Another feature of the new version is that it supports OpenGL rendering.

I am closing this issue. Feel free to open a new issue or reopen this issue if you have any questions or problems with SPARK.
