### ISSUE TITLE
model availability : liver fibrosis ABM (LFABM) SPARK model

### ISSUE THREAD

**Issue by jperales** [monadius/spark-abm#2]
Dear @monadius ,
I am fascinated with your publication "A multiscale agent-based in silico model of liver fibrosis progression" (2014), and the model presented in that publication. I wonder where I could find the model. Unfortunately the original link to download the model is broken (http://www.pitt.edu/~cirm/spark/models/LFABM.zip), and if I didn't miss it, the current version of spark does not include it among the samples (models). Could you please share with me the original model or any other new version of LFABM?

Thank you very much
Best,
Javier

**Comment by monadius** [comment]
Hi @jperales,

You can download the model from my Google drive:
https://drive.google.com/file/d/16GkWGhmzLat0PTX31_qLtpyP3q9l5LRg/view?usp=sharing

The archive contains a complete SPARK distribution and the model itself (in the folder CirrhosisModel). You may try the SPARK distribution from the archive to run the model:

1) Install JDK if you don't have it (I recommend OpenJDK 8 or 11 from https://adoptopenjdk.net/releases.html)
2) Run `SPARK Manager.jar` (double click it or type in the command line `java -jar "SPARK Manager.jar"`).
3) Go to `Options -> Options`. Set paths to `spark-core.jar` and `spark-external.jar` (open file selection dialogs and select corresponding files `lib/spark-core.jar` and `lib/spark-external.jar`).
4) Select `File -> Open` and open `CirrhosisModel/CirrhosisModel.xml`.
5) Now click "Run in SPARK" to run the model. Click "Start" when the model is loaded.

Another option is to use the latest SPARK distribution.

1) Follow installation steps from https://github.com/monadius/spark-abm#how-to-run
2) Run `SPARK_Manager.jar` and open the model (from `CirrhosisModel/CirrhosisModel.xml`).
3) Now click "Start" to run the model. It will recompile the model and open it in SPARK. Click "Start" when the model is loaded.

Let me know if you get any problems with SPARK.

Best,
Alexey
